
package webservice.animal.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AnimalService", targetNamespace = "http://impl.service.webservice.my/", wsdlLocation = "http://localhost:8000/ws/animal?wsdl")
public class AnimalServiceImpl
    extends Service
{

    private final static URL ANIMALSERVICE_WSDL_LOCATION;
    private final static WebServiceException ANIMALSERVICE_EXCEPTION;
    private final static QName ANIMALSERVICE_QNAME = new QName("http://impl.service.webservice.my/", "AnimalService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8000/ws/animal?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ANIMALSERVICE_WSDL_LOCATION = url;
        ANIMALSERVICE_EXCEPTION = e;
    }

    public AnimalServiceImpl() {
        super(__getWsdlLocation(), ANIMALSERVICE_QNAME);
    }

    public AnimalServiceImpl(WebServiceFeature... features) {
        super(__getWsdlLocation(), ANIMALSERVICE_QNAME, features);
    }

    public AnimalServiceImpl(URL wsdlLocation) {
        super(wsdlLocation, ANIMALSERVICE_QNAME);
    }

    public AnimalServiceImpl(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ANIMALSERVICE_QNAME, features);
    }

    public AnimalServiceImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AnimalServiceImpl(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AnimalService
     */
    @WebEndpoint(name = "AnimalPort")
    public AnimalService getAnimalPort() {
        return super.getPort(new QName("http://impl.service.webservice.my/", "AnimalPort"), AnimalService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AnimalService
     */
    @WebEndpoint(name = "AnimalPort")
    public AnimalService getAnimalPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.service.webservice.my/", "AnimalPort"), AnimalService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ANIMALSERVICE_EXCEPTION!= null) {
            throw ANIMALSERVICE_EXCEPTION;
        }
        return ANIMALSERVICE_WSDL_LOCATION;
    }

}
