
package webservice.animal.impl;

import webservice.animal.Cat;
import webservice.animal.ObjectFactory;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AnimalService", targetNamespace = "http://service.webservice.my/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AnimalService {


    /**
     * 
     * @param arg0
     * @return
     *     returns my.webservice.service.Cat
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCat", targetNamespace = "http://service.webservice.my/", className = "webservice.animal.GetCat")
    @ResponseWrapper(localName = "getCatResponse", targetNamespace = "http://service.webservice.my/", className = "webservice.animal.GetCatResponse")
    @Action(input = "http://service.webservice.my/AnimalService/getCatRequest", output = "http://service.webservice.my/AnimalService/getCatResponse")
    public Cat getCat(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
